@startuml activity_for_data
start

:Запуск программы;
:Инициализация массива контактов;

repeat :while ВЫБОР != "Выход"
    :Показать меню пользователю;
    :Получить выбор пользователя;

    switch (Выбор)
        case (1. Ввод контакта)
            :Запрос данных контакта;
            :Создать запись Contact;
            :Добавить запись в массив;
            
        case (2. Вывод списка контактов)
            :Показать все элементы массива;
            
        case (3. Сохранить файл)
            :Запрос имени файла;
            :Запрос режима (новый / добавить);
            
            if (mode = новый файл?) then (да)
                :Открыть файл в режиме перезаписи;
                :Записать все контакты;
            else (нет)
                :Открыть файл в режиме append;
                if (Файл найден?) then (да)
                    :Добавить новые записи в конец файла;
                else (нет)
                    :Сообщить об ошибке "Файл не найден";
                endif
            endif

            
        case (4. Загрузить из файла)
            :Запрос имени файла;
            :Открыть файл;
            if (Файл открыт?) then (да)
                :Считать контакты построчно;
                :Разобрать строку по разделителям;
                :Создать записи Contact;
                :Добавить их в массив;
            else (нет)
                :Сообщить об ошибке;
            endif

        case (0. Выход)
            stop
    endswitch

repeat while (не выбран пункт "Выход")

@enduml
